---
- name: Start Nginx
  hosts: production
  become: yes
  tasks:
    - name: Start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
      
    - name: Check Nginx status
      systemd:
        name: nginx
      register: nginx_status
    
    - name: Display Nginx status
      debug:
        msg: "Nginx is {{ nginx_status.status.ActiveState }}"
    
    - name: Verify port 80 is listening
      shell: netstat -tlnp 2>/dev/null | grep 80 || ss -tlnp 2>/dev/null | grep 80
      register: port_check
      ignore_errors: yes
    
    - name: Display port 80 status
      debug:
        msg: "{{ port_check.stdout_lines }}"
