#!/bin/bash

echo "============================================="
echo "Cloudflare Tunnel Quick Setup"
echo "============================================="
echo ""
echo "Current situation:"
echo "  - Domain: my-resume.paskot.com"
echo "  - DNS points to: Cloudflare proxy (172.67.182.240)"
echo "  - Server IP: 172.16.23.127"
echo "  - Services: Running on 172.16.23.127"
echo ""
echo "Problem: Cloudflare tunnel not configured to forward traffic"
echo ""
echo "============================================="
echo "OPTION 1: Quick Fix - Disable Cloudflare Proxy"
echo "============================================="
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select domain: paskot.com"
echo "3. Go to: DNS > Records"
echo "4. Find record: my-resume.paskot.com"
echo "5. Click the orange cloud (Proxied) to change to gray cloud (DNS only)"
echo "6. Update IP address to: 172.16.23.127"
echo "7. Save"
echo ""
echo "Wait 5 minutes for DNS propagation, then test:"
echo "  curl -I http://my-resume.paskot.com"
echo ""
echo "============================================="
echo "OPTION 2: Setup Cloudflare Tunnel (Recommended)"
echo "============================================="
echo ""
echo "This requires interactive login. Run these commands on the server:"
echo ""
echo "# 1. SSH to server"
echo "ssh jose@172.16.23.127"
echo ""
echo "# 2. Install cloudflared (if not installed)"
echo "curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb"
echo "sudo dpkg -i cloudflared.deb"
echo ""
echo "# 3. Login to Cloudflare (opens browser)"
echo "sudo cloudflared tunnel login"
echo ""
echo "# 4. Create tunnel"
echo "sudo cloudflared tunnel create my-resume-tunnel"
echo ""
echo "# 5. Note the TUNNEL-ID from the output above, then create config:"
echo "sudo mkdir -p /etc/cloudflared"
echo "sudo nano /etc/cloudflared/config.yml"
echo ""
echo "# Add this content (replace <TUNNEL-ID> with actual ID):"
cat << 'EOF'

tunnel: <TUNNEL-ID>
credentials-file: /root/.cloudflared/<TUNNEL-ID>.json

ingress:
  - hostname: my-resume.paskot.com
    service: http://localhost:80
  - hostname: www.my-resume.paskot.com
    service: http://localhost:80
  - service: http_status:404

EOF
echo ""
echo "# 6. Route DNS"
echo "sudo cloudflared tunnel route dns my-resume-tunnel my-resume.paskot.com"
echo ""
echo "# 7. Start tunnel as service"
echo "sudo cloudflared service install"
echo "sudo systemctl start cloudflared"
echo "sudo systemctl enable cloudflared"
echo ""
echo "# 8. Check status"
echo "sudo systemctl status cloudflared"
echo ""
echo "============================================="
echo "OPTION 3: Test Locally First"
echo "============================================="
echo ""
echo "Test if services work locally:"
echo "  curl http://172.16.23.127"
echo "  curl http://172.16.23.127/api/health"
echo ""
echo "Add to /etc/hosts for local testing:"
echo "  172.16.23.127  my-resume.paskot.com"
echo ""
echo "============================================="
