#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "  Fix Custom Subdomain Support for resumecast.ai"
echo "═══════════════════════════════════════════════════════════"
echo ""

SERVER="jose@172.16.23.127"

echo "📋 Current Status:"
echo "  - API Backend: ✅ Working (tested /api/resumes/by-domain/jose-blanco)"
echo "  - Frontend: ✅ Built with PUBLIC_BASE_DOMAIN=resumecast.ai"
echo "  - Nginx: ❌ Missing wildcard subdomain support"
echo "  - DNS: ⚠️  Points to Cloudflare (needs tunnel route configured)"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  OPTION 1: Apply Nginx Config (Requires Sudo)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "The nginx config with subdomain support is ready at:"
echo "  /tmp/nginx-myresume.conf (on server)"
echo ""
echo "To apply it, SSH to the server and run:"
echo ""
echo "  ssh $SERVER"
echo "  sudo cp /tmp/nginx-myresume.conf /etc/nginx/sites-available/myresume"
echo "  sudo nginx -t"
echo "  sudo systemctl reload nginx"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  OPTION 2: Configure Cloudflare Tunnel Route"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Since DNS points to Cloudflare, you need to configure the tunnel:"
echo ""
echo "1. Go to: https://one.dash.cloudflare.com/"
echo "2. Navigate to: Networks → Tunnels"
echo "3. Find your tunnel for resumecast.ai"
echo "4. Click 'Configure' → 'Public Hostnames'"
echo "5. Add a public hostname:"
echo ""
echo "   Subdomain: *"
echo "   Domain: resumecast.ai"
echo "   Path: (leave empty)"
echo "   Service Type: HTTP"
echo "   URL: localhost:80"
echo ""
echo "6. Save"
echo ""
echo "This will route ALL subdomains (*.resumecast.ai) to your server."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  Testing After Fix"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Once either option is applied, test with:"
echo ""
echo "  curl -I http://jose-blanco.resumecast.ai"
echo "  curl http://localhost:3000/api/resumes/by-domain/jose-blanco"
echo ""
echo "The subdomain should:"
echo "  1. Resolve to your server (via Cloudflare tunnel)"
echo "  2. Be accepted by nginx (with wildcard support)"
echo "  3. Frontend detects 'jose-blanco' subdomain"
echo "  4. Calls /api/resumes/by-domain/jose-blanco"
echo "  5. Returns resume content"
echo ""

echo "═══════════════════════════════════════════════════════════"
